/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSidebar: typeof import('./src/components/AI/AiSidebar.vue')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    Bread: typeof import('./src/components/Bread.vue')['default']
    Chat: typeof import('./src/components/AI/Chat.vue')['default']
    Editor: typeof import('./src/components/ppt/editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImgUpload: typeof import('./src/components/mindmap/ImgUpload/index.vue')['default']
    Ocr: typeof import('./src/components/AI/Ocr.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/ppt/slider.vue')['default']
    Translate: typeof import('./src/components/AI/Translate.vue')['default']
    Vtoc: typeof import('./src/components/AI/vtoc.vue')['default']
    Write: typeof import('./src/components/AI/Write.vue')['default']
  }
}
